import { defineComponent, ref } from "vue";
import { 
  TwitterOutlined,
  InstagramOutlined,
  AntCloudOutlined,
  SoundFilled,
  Popover,
  // Button
  } from "@ant-design/icons-vue";

import "./Home.css";
import Img from '../assets/images/0.png'
import Unnamed from '../assets/images/unnamed.jpeg'
import wallet from '../assets/images/wallet.svg'
const Home = defineComponent(()=>{
  
  const tilteList = ref([
    "https://doodles.app/images/doodles_logo.png",
    "https://doodles.app/images/doodlebank_logo.png",
    "https://doodles.app/images/shopdoodles_logo.png",
    "https://doodles.app/images/spacedoodles_logo.png",
  ]);
  const visible = ref(false);
  
  const showModal = () => {
    visible.value = true;
  };

  const onCloseMask = () => {
    console.log('mask');
    visible.value = false;
  }

  const Coinbase = (e) => {
    enterMask()
  }

  const WalletConnect = () => {
    console.log(234)
  }
  const show = ref(false)
  const enterMask = () => {
    console.log('enterMask');
    show.value = true
  }
  const render = () => {
    return(
      <>
        <header className="header">
          <div className="headerCon">
              <div className="headerTitle">
                {tilteList.value.map((item) => {
                  return <img className={"headerImg"} src={item} alt="" />;
                })}
              </div>
            <div className="headerDocs" style={{marginLeft:'36px'}}>DOCS</div>
            <div className="headerDocs">
              <a-popover
                content={
                  <div className="contentText">
                    <p onClick={()=>window.open('https://www.baidu.com','_blank')}>OpenSea</p>
                    <p>Nifty Gateway</p>
                    <p>LooksRare</p>
                  </div>
                }
                trigger="click"
                // visible={visible.value}
              >
                <div >BUY A DOOBLE</div>
              </a-popover>
            </div>
            <div className="headerIcon">
              <div className='icon'>
                <TwitterOutlined  style={{color:'#fff',fontSize:'24px'}}/>
              </div>
              <div className='icon'>
                <AntCloudOutlined style={{color:'#fff',fontSize:'24px'}}/>
              </div>
              <div className='icon'>
                <InstagramOutlined style={{color:'#fff',fontSize:'24px'}}/>
              </div>
            </div>
            <div className="headerConnect" onClick={showModal}>
                Connect
            </div>
           
            
            <div className='icon' style={{marginLeft:'18px'}}>
              <SoundFilled style={{color:'#fff',fontSize:'24px'}}/>
            </div>
          </div>
        </header>
        {/* model 显示 */}
        {
          visible.value ? (
            <div>
              <div className="mask" onClick={onCloseMask}> </div>
              <div className="conenctShow">
                  <div className="connectText" onClick={()=>{WalletConnect()}}><img className="connectImg" src={Unnamed}/><text >WalletConnect</text></div>
                  <div className="connectText" onClick={()=>{Coinbase()}}><img className="connectImg" src={wallet}/><text >Coinbase</text></div>
                </div>
            </div>
          ):''
        }
        <div  className="center">
          <div className="introduction">
            <div className="info">HyperDog</div>
            <div className="info">Born in the Web3 world, HyperDog is a collection of 10,000 unusually super-excited avatars with richly diverse rarity-backed features.</div>
            <div className="info">Holding a vision of driving the universe HYPER, HyperDog is created for builders, artists, and pioneers of a decentralized future. Like dopamine, HYPER is spiritual energy generated by each of HyperDog to deliver optimism, passion, and creativity. </div>
            <div className="info">Let’s go HYPER together! Let’s build together!</div>
          </div>
          <img className="ufo" src={Img}/> 
        </div>
        <div className="footer" style={{marginTop:'64px'}}>
            <div className="footerFir">YOUR FRENS THROUGH THE METAVERSE</div>
            <div className="footerSec">The Doodles Founders</div>
            <div className="footerThi">
              <div className="footerBox">
                <img src="https://doodles.app/images/doodle_poopie.png"/>
                <div className="footerUrl">@evankeast</div>
                <div className="footerName">EVAN KEAST</div>
                <div className="footerContent">Also known as Tulip in the community, Evan is a Canadian-based product marketer and NFT consultant. Evan comes from Kabam Games (Net Marble), Dapper Labs, and CryptoKitties.</div>
              </div>
              <div className="footerBox">
                <img src="https://doodles.app/images/doodle_poopie.png"/>
                <div className="footerUrl">@evankeast</div>
                <div className="footerName">EVAN KEAST</div>
                <div className="footerContent">Also known as Tulip in the community, Evan is a Canadian-based product marketer and NFT consultant. Evan comes from Kabam Games (Net Marble), Dapper Labs, and CryptoKitties.</div>
              </div>
              <div className="footerBox">
                <img src="https://doodles.app/images/doodle_poopie.png"/>
                <div className="footerUrl">@evankeast</div>
                <div className="footerName">EVAN KEAST</div>
                <div className="footerContent">Also known as Tulip in the community, Evan is a Canadian-based product marketer and NFT consultant. Evan comes from Kabam Games (Net Marble), Dapper Labs, and CryptoKitties.</div>
              </div>
            </div>
        </div>
        <footer>
        Created by the Doodles Founders with special ♥ to our developer partners, West Coast NFT, our moderators, alfie, disclosure, and the support from the community, our friends, families, and loved ones.
        For all press inquiries, please contact press@doodles.app
        </footer>
      </>
    )
     
  }
  return render
})

export default Home;
